"""first_initialisation

Revision ID: cc1b91ad445a
Revises: 
Create Date: 2026-05-10 10:31:44.535162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cc1b91ad445a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xflow_steps')
    op.drop_index(op.f('ix_product_reference'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_xflow_audit_logs_run_id'), table_name='xflow_audit_logs')
    op.drop_table('xflow_audit_logs')
    op.drop_table('shipment_items')
    op.drop_index(op.f('ix_movement_product'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_xflow_flows_name'), table_name='xflow_flows')
    op.drop_table('xflow_flows')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_xform_views_form_id'), table_name='xform_views')
    op.drop_table('xform_views')
    op.drop_table('orders')
    op.drop_index(op.f('ix_xflow_runs_status'), table_name='xflow_runs')
    op.drop_table('xflow_runs')
    op.drop_index(op.f('ix_xform_pipeline_logs_form_id'), table_name='xform_pipeline_logs')
    op.drop_index(op.f('ix_xform_pipeline_logs_submission_id'), table_name='xform_pipeline_logs')
    op.drop_table('xform_pipeline_logs')
    op.drop_table('shipments')
    op.drop_table('xflow_dead_jobs')
    op.drop_table('xflow_versions')
    op.drop_index(op.f('ix_xflow_composites_name'), table_name='xflow_composites')
    op.drop_table('xflow_composites')
    op.drop_table('xflow_schedules')
    op.drop_table('categories')
    op.drop_table('locations')
    op.drop_index(op.f('ix_xform_submissions_created_at'), table_name='xform_submissions')
    op.drop_index(op.f('ix_xform_submissions_form_id'), table_name='xform_submissions')
    op.drop_index(op.f('ix_xform_submissions_status'), table_name='xform_submissions')
    op.drop_table('xform_submissions')
    op.drop_table('inventory_levels')
    op.drop_index(op.f('ix_xform_forms_owner_id'), table_name='xform_forms')
    op.drop_index(op.f('ix_xform_forms_slug'), table_name='xform_forms')
    op.drop_index(op.f('ix_xform_forms_status'), table_name='xform_forms')
    op.drop_table('xform_forms')
    op.drop_table('suppliers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('xform_forms',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('fields', sqlite.JSON(), nullable=False),
    sa.Column('steps', sqlite.JSON(), nullable=False),
    sa.Column('settings', sqlite.JSON(), nullable=False),
    sa.Column('theme', sqlite.JSON(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xform_forms_status'), 'xform_forms', ['status'], unique=False)
    op.create_index(op.f('ix_xform_forms_slug'), 'xform_forms', ['slug'], unique=1)
    op.create_index(op.f('ix_xform_forms_owner_id'), 'xform_forms', ['owner_id'], unique=False)
    op.create_table('inventory_levels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('safety_stock', sa.INTEGER(), nullable=False),
    sa.Column('min_level', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name=op.f('uq_product_location'))
    )
    op.create_table('xform_submissions',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('form_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['xform_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xform_submissions_status'), 'xform_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_xform_submissions_form_id'), 'xform_submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_xform_submissions_created_at'), 'xform_submissions', ['created_at'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('xflow_schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flow_id', sa.INTEGER(), nullable=False),
    sa.Column('cron', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_run_at', sa.DATETIME(), nullable=True),
    sa.Column('next_run_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['xflow_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xflow_composites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=64), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('definition', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xflow_composites_name'), 'xflow_composites', ['name'], unique=1)
    op.create_table('xflow_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flow_id', sa.INTEGER(), nullable=False),
    sa.Column('version_tag', sa.VARCHAR(length=64), nullable=False),
    sa.Column('definition', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['xflow_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xflow_dead_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shipment_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source_location_id', sa.INTEGER(), nullable=False),
    sa.Column('destination_location_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('departure_date', sa.DATETIME(), nullable=True),
    sa.Column('estimated_arrival_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_arrival_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_table('xform_pipeline_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submission_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('form_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('step', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('executed_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['xform_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xform_pipeline_logs_submission_id'), 'xform_pipeline_logs', ['submission_id'], unique=False)
    op.create_index(op.f('ix_xform_pipeline_logs_form_id'), 'xform_pipeline_logs', ['form_id'], unique=False)
    op.create_table('xflow_runs',
    sa.Column('run_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('version_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('trigger_data', sqlite.JSON(), nullable=False),
    sa.Column('context', sqlite.JSON(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['xflow_versions.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_xflow_runs_status'), 'xflow_runs', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('order_date', sa.DATETIME(), nullable=False),
    sa.Column('expected_delivery_date', sa.DATETIME(), nullable=True),
    sa.Column('received_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('xform_views',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('form_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=512), nullable=True),
    sa.Column('viewed_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['xform_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xform_views_form_id'), 'xform_views', ['form_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_item_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name=op.f('uq_order_item_product'))
    )
    op.create_table('xflow_flows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xflow_flows_name'), 'xflow_flows', ['name'], unique=1)
    op.create_table('stock_movements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('quantity_before', sa.INTEGER(), nullable=False),
    sa.Column('quantity_after', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reference_doc', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_movement_quantity_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_product'), 'stock_movements', ['product_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shipment_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xflow_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('level', sa.VARCHAR(length=16), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xflow_audit_logs_run_id'), 'xflow_audit_logs', ['run_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reference', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('purchase_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('quantity_in_stock', sa.INTEGER(), nullable=False),
    sa.Column('alert_threshold', sa.INTEGER(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint('purchase_price >= 0', name=op.f('ck_product_purchase_price_positive')),
    sa.CheckConstraint('sale_price >= 0', name=op.f('ck_product_sale_price_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_product_reference'), 'products', ['reference'], unique=False)
    op.create_table('xflow_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('step_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('step_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('input_data', sqlite.JSON(), nullable=True),
    sa.Column('output_data', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['xflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
